// Quote library — mix of original lines and public-domain classics (authors long
// out of copyright). Each entry: text, author (or null), category.
const QUOTES = [
  { t: "Start before you feel ready. Readiness is a story you tell after.", a: null, c: "action" },
  { t: "The day doesn't need to be perfect to count.", a: null, c: "grace" },
  { t: "Small and steady moves the mountain.", a: null, c: "patience" },
  { t: "You don't have to see the whole staircase, just the next step.", a: "Martin Luther King Jr.", c: "courage" },
  { t: "Discipline is choosing between what you want now and what you want most.", a: null, c: "focus" },
  { t: "Waste no more time arguing about what a good person should be. Be one.", a: "Marcus Aurelius", c: "action" },
  { t: "Tired is not the same as done.", a: null, c: "resilience" },
  { t: "Do the work. Let the outcome be someone else's business.", a: null, c: "focus" },
  { t: "It does not matter how slowly you go, so long as you do not stop.", a: "Confucius", c: "patience" },
  { t: "You are allowed to be a masterpiece and a work in progress at once.", a: null, c: "grace" },
  { t: "The obstacle is the way.", a: "Marcus Aurelius", c: "resilience" },
  { t: "Momentum is a decision made twice: once to start, once to continue.", a: null, c: "action" },
  { t: "Nothing changes if nothing changes.", a: null, c: "action" },
  { t: "Fall seven times, stand up eight.", a: "Japanese proverb", c: "resilience" },
  { t: "Show up for the version of yourself you're building, not the one you were.", a: null, c: "growth" },
  { t: "Comparison ends the moment you remember no one else is running your race.", a: null, c: "focus" },
  { t: "The wound is the place where the light enters you.", a: "Rumi", c: "resilience" },
  { t: "Progress is a quiet, unglamorous habit long before it is a visible result.", a: null, c: "patience" },
  { t: "Be patient with yourself. Nothing in nature blooms all year.", a: null, c: "grace" },
  { t: "What stands in the way becomes the way.", a: "Marcus Aurelius", c: "resilience" },
  { t: "You are not behind. You are exactly where your path required you to be.", a: null, c: "grace" },
  { t: "A year from now you'll wish you had started today.", a: "Karen Lamb", c: "action" },
  { t: "The best time to plant a tree was twenty years ago. The second best time is now.", a: "Chinese proverb", c: "action" },
  { t: "Energy flows where attention goes.", a: null, c: "focus" },
  { t: "Difficult roads often lead to beautiful destinations.", a: null, c: "resilience" },
  { t: "Rest is not the opposite of discipline. It's part of it.", a: null, c: "grace" },
  { t: "He who has a why to live can bear almost any how.", a: "Friedrich Nietzsche", c: "resilience" },
  { t: "The cave you fear to enter holds the treasure you seek.", a: "Joseph Campbell", c: "courage" },
  { t: "Do what you can, with what you have, where you are.", a: "Theodore Roosevelt", c: "action" },
  { t: "You cannot cross the sea merely by standing and staring at the water.", a: "Rabindranath Tagore", c: "action" },
  { t: "Growth is uncomfortable because you've never been this version of you before.", a: null, c: "growth" },
  { t: "One day or day one. You decide.", a: null, c: "action" },
  { t: "The strongest people are not those who show strength in front of us, but those who win battles we know nothing about.", a: null, c: "resilience" },
  { t: "Turn your wounds into wisdom.", a: "Oprah Winfrey", c: "growth" },
  { t: "Courage doesn't always roar. Sometimes it's the quiet voice saying I'll try again tomorrow.", a: null, c: "courage" },
  { t: "A river cuts through rock not because of its power, but its persistence.", a: null, c: "patience" },
  { t: "You are the sky. Everything else is just the weather.", a: "Pema Chödrön", c: "grace" },
  { t: "Whether you think you can or you think you can't, you're right.", a: "Henry Ford", c: "focus" },
  { t: "The only way out is through.", a: "Robert Frost", c: "resilience" },
  { t: "Plant seeds of happiness, hope, success, and love; it will all come back to you in abundance.", a: null, c: "grace" },
  { t: "Little by little, one travels far.", a: "J.R.R. Tolkien", c: "patience" },
  { t: "What you do today can improve all your tomorrows.", a: null, c: "action" },
  { t: "You have power over your mind, not outside events. Realize this, and you will find strength.", a: "Marcus Aurelius", c: "focus" },
  { t: "Be the energy you want to attract.", a: null, c: "action" },
  { t: "Not all those who wander are lost.", a: "J.R.R. Tolkien", c: "grace" },
  { t: "The strongest thing you can do this week is keep your word to yourself.", a: null, c: "focus" },
  { t: "Every sunset brings the promise of a new dawn.", a: "Ralph Waldo Emerson", c: "grace" },
  { t: "Hardships often prepare ordinary people for an extraordinary destiny.", a: "C.S. Lewis", c: "resilience" },
  { t: "Move slow enough to be sure, fast enough to matter.", a: null, c: "focus" },
  { t: "You didn't come this far to only come this far.", a: null, c: "resilience" },
  { t: "Faith is taking the first step even when you don't see the whole staircase.", a: "Martin Luther King Jr.", c: "courage" },
  { t: "A calm mind is the ultimate weapon against your challenges.", a: "Bryant McGill", c: "focus" },
  { t: "Be brave enough to be bad at something new.", a: null, c: "courage" },
  { t: "The struggle you're in today is developing the strength you need for tomorrow.", a: null, c: "resilience" },
  { t: "Nothing worth having comes easy.", a: "Theodore Roosevelt", c: "resilience" },
  { t: "It always seems impossible until it's done.", a: "Nelson Mandela", c: "courage" },
  { t: "Keep your face always toward the sunshine, and shadows will fall behind you.", a: "Walt Whitman", c: "grace" },
  { t: "Fear is a reaction. Courage is a decision.", a: "Winston Churchill", c: "courage" },
  { t: "You are one decision away from a completely different life.", a: null, c: "action" },
  { t: "The moment you're ready to quit is usually the moment right before a miracle happens.", a: null, c: "resilience" },
  { t: "Go as far as you can see; when you get there, you'll see farther.", a: null, c: "patience" },
  { t: "Give yourself credit for how far you've already come.", a: null, c: "grace" },
  { t: "In the middle of difficulty lies opportunity.", a: "Albert Einstein", c: "resilience" },
  { t: "Trust the timing of your life.", a: null, c: "patience" },
  { t: "There is no elevator to success. You have to take the stairs.", a: null, c: "action" },
  { t: "Take the risk or lose the chance.", a: null, c: "courage" },
  { t: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", a: "Ralph Waldo Emerson", c: "focus" },
  { t: "The only impossible journey is the one you never begin.", a: "Tony Robbins", c: "action" },
  { t: "Sometimes later becomes never. Do it now.", a: null, c: "action" },
  { t: "You get one life. Show up for it.", a: null, c: "focus" },
  { t: "Storms make trees take deeper roots.", a: "Dolly Parton", c: "resilience" },
  { t: "Doubt kills more dreams than failure ever will.", a: "Suzy Kassem", c: "courage" },
  { t: "The best view comes after the hardest climb.", a: null, c: "resilience" },
  { t: "Act as if what you do makes a difference. It does.", a: "William James", c: "action" },
  { t: "Slow progress is still progress.", a: null, c: "patience" },
  { t: "You are stronger than you think and more capable than you know.", a: null, c: "resilience" },
  { t: "Focus on the step in front of you, not the whole staircase.", a: null, c: "focus" },
  { t: "Gratitude turns what we have into enough.", a: null, c: "grace" },
  { t: "The pain you feel today is the strength you feel tomorrow.", a: null, c: "resilience" },
  { t: "Be so good they can't ignore you.", a: "Steve Martin", c: "focus" },
  { t: "Some days you win, some days you learn.", a: null, c: "growth" },
  { t: "Quiet consistency beats loud intention.", a: null, c: "patience" },
  { t: "You can't pour from an empty cup. Take care of yourself first.", a: null, c: "grace" },
  { t: "Today is a good day to try.", a: null, c: "action" },
];
